"""News data loader for GeoQuant AI -- unified historical news source."""

from __future__ import annotations

import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import pandas as pd

from config import NEWS_AGGREGATED_FILE, NEWS_PROCESSED_FILE


@dataclass
class NewsLoader:
    """
    Load, clean, and aggregate the historical news source used by GeoQuant AI.

    By default, Bloc 1 now reads the processed unified historical news file
    generated by `news_main.py` so that the historical chain is fully aligned:
        news -> Geo-Score -> strategy -> backtest -> dashboard
    """

    base_dir: Path
    news_file: Optional[Path] = None
    date_col: str = "date"
    title_col: str = "headline"

    _KNOWN_DATE_COLS: list[str] = field(
        default_factory=lambda: [
            "date", "Date", "published", "publishedAt",
            "datetime", "timestamp", "pub_date", "Datetime",
        ]
    )
    _KNOWN_TITLE_COLS: list[str] = field(
        default_factory=lambda: [
            "headline", "Headline", "title", "Title",
            "text", "Text", "content", "Content", "description",
        ]
    )

    def _default_news_path(self) -> Path:
        """Return the default processed Kaggle news CSV path."""
        return self.base_dir / "data" / "processed" / NEWS_PROCESSED_FILE

    def _resolve_path(self) -> Path:
        """Return the resolved absolute path to the news file."""
        if self.news_file is None:
            return self._default_news_path()
        path = Path(self.news_file)
        return path if path.is_absolute() else self.base_dir / path

    def _detect_columns(self, df: pd.DataFrame) -> tuple[str, str]:
        """Auto-detect date and headline columns from the source DataFrame."""
        date_col: Optional[str] = None
        title_col: Optional[str] = None

        for candidate in self._KNOWN_DATE_COLS:
            if candidate in df.columns:
                date_col = candidate
                break

        for candidate in self._KNOWN_TITLE_COLS:
            if candidate in df.columns:
                title_col = candidate
                break

        if date_col is None:
            raise ValueError(
                f"Cannot auto-detect date column. Available columns: {list(df.columns)}"
            )
        if title_col is None:
            raise ValueError(
                f"Cannot auto-detect title column. Available columns: {list(df.columns)}"
            )

        return date_col, title_col

    def load_raw(self) -> pd.DataFrame:
        """Load the news CSV from disk."""
        path = self._resolve_path()
        if not path.exists():
            raise FileNotFoundError(
                f"News file not found: {path}\n"
                "Run `python src/news_main.py` first or pass news_file= to NewsLoader."
            )

        df = pd.read_csv(path, encoding="utf-8")

        if self.date_col not in df.columns or self.title_col not in df.columns:
            detected_date, detected_title = self._detect_columns(df)
            print(
                f"  [NewsLoader] Auto-detected columns: "
                f"date='{detected_date}', title='{detected_title}'"
            )
            self.date_col = detected_date
            self.title_col = detected_title

        return df

    def clean(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Clean and standardise the news table.

        Returns a DataFrame with at least:
            date | headline
        """
        df = df.copy()

        rename_map: dict[str, str] = {}
        if self.date_col != "date":
            rename_map[self.date_col] = "date"
        if self.title_col != "headline":
            rename_map[self.title_col] = "headline"
        if rename_map:
            df = df.rename(columns=rename_map)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            df["date"] = pd.to_datetime(df["date"], errors="coerce")

        before = len(df)
        df = df.dropna(subset=["date"])
        dropped_dates = before - len(df)
        if dropped_dates:
            print(f"  [NewsLoader] Dropped {dropped_dates} rows with invalid dates.")

        df["headline"] = df["headline"].astype(str).str.strip()
        df = df[~df["headline"].isin(["", "nan", "NaN", "None"])]
        dropped_titles = (before - dropped_dates) - len(df)
        if dropped_titles:
            print(f"  [NewsLoader] Dropped {dropped_titles} rows with empty titles.")

        before_dedup = len(df)
        df = df.drop_duplicates(subset=["date", "headline"])
        dropped_dedup = before_dedup - len(df)
        if dropped_dedup:
            print(f"  [NewsLoader] Dropped {dropped_dedup} duplicate rows.")

        df["date"] = df["date"].dt.normalize()
        df = df.sort_values("date").reset_index(drop=True)
        return df

    def aggregate_by_day(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Aggregate cleaned headlines by day for the historical market dataset.

        Output columns:
            date | nb_articles | titles | news
        """
        grouped = (
            df.groupby("date")
            .agg(
                nb_articles=("headline", "count"),
                titles=("headline", lambda x: " | ".join(x)),
            )
            .reset_index()
        )
        grouped["news"] = grouped["titles"]
        grouped = grouped.sort_values("date").reset_index(drop=True)
        return grouped

    def save_aggregated(
        self,
        df: pd.DataFrame,
        filename: str = NEWS_AGGREGATED_FILE,
    ) -> Path:
        """Persist the aggregated daily news table."""
        processed_dir = self.base_dir / "data" / "processed"
        processed_dir.mkdir(parents=True, exist_ok=True)
        output_path = processed_dir / filename
        df.to_csv(output_path, index=False)
        print(f"  [NewsLoader] Saved aggregated news -> {output_path}")
        return output_path

    def run(self) -> pd.DataFrame:
        """Execute load -> clean -> aggregate -> save."""
        print("[NewsLoader] Loading historical news source...")
        raw = self.load_raw()
        print(f"  Loaded {len(raw)} raw articles.")

        print("[NewsLoader] Cleaning...")
        cleaned = self.clean(raw)
        print(f"  {len(cleaned)} articles after cleaning.")

        print("[NewsLoader] Aggregating by day...")
        aggregated = self.aggregate_by_day(cleaned)
        print(f"  {len(aggregated)} days with news.")

        self.save_aggregated(aggregated)
        return aggregated
